apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ard-mcp
  namespace: ard-mcp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ard-mcp
  minReplicas: 2
  maxReplicas: x # <-- anpassen auf die max Anzahl der pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
